routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('route:clear');
    dd(Artisan::output());
});

// Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
// Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
// Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
// Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
// Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
// Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');
// Route::post('/set-password', 'CommonController@changePassword')->name('set-password');
//Before authentication
Route::group(['middleware' => 'beforeAuth'], function () {
    Route::get('/login', 'Admin\UsersController@login');
    Route::get('/backend', 'Admin\UsersController@login');
    Route::get('backend/login', 'Admin\UsersController@login')->name('backend.login');
    Route::get('backend/forgotPassword', 'Admin\UsersController@recoverPassword');
    Route::get('backend/resetPassword/{token}', 'Admin\UsersController@resetPassword');


    Route::post('login', 'Admin\UsersController@login');
    Route::post('recoverPassword', 'Admin\UsersController@recoverPassword');

    //client routes
    Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
    Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
    Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
    Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
    Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
    Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');

    Route::post('/set-password', 'CommonController@changePassword')->name('set-password');

    Route::get('change-password', 'CommonController@changeClientPassword');
    Route::post('changeClientOldPassword', 'CommonController@changeClientPassword');

    Route::get('resetPasswordClient/{token}', 'CommonController@resetPassword');
    Route::get('client-forgotPassword', 'CommonController@recoverPassword');
    Route::post('client-recoverPassword', 'CommonController@recoverPassword');

    Route::get('client-generate-work-order', 'TaskController@GenerateWorkOrder')->name('client.generate.work.order');
});


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function () {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list', 'Admin\UsersController@index')->name('users.index');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard/{type?}', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');

    Route::resource('properties', 'PropertyController');
    Route::match(['get', 'post'], '/property-list', 'PropertyController@index')->name('property.index');

    Route::resource('clients', 'ClientController');
    Route::match(['get', 'post'], '/client-list', 'ClientController@index')->name('client.index');

    Route::resource('client_properties', 'ClientPropertyController');
    Route::match(['get', 'post'], '/client-property-list', 'ClientPropertyController@index')->name('client_properties.index');


    Route::resource('leads', 'LeadController');
    Route::get('/arcive-lead/{id?}', 'LeadController@archive_lead')->name('lead.archive');
    Route::match(['get', 'post'], '/lead-list', 'LeadController@index')->name('lead.index');


    // Route::get('tasks', 'TaskController@index')->name('task.index');
    // Route::post('tasks-check', 'TaskController@index')->name('task.check');
    Route::match(['get', 'post'], '/task-list/{type?}', 'TaskController@index')->name('task.index');
    Route::get('get-client', 'TaskController@getClientInfo')->name('get.client.info');
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/{id}/edit/{completed?}', 'TaskController@edit')->name('tasks.edit');
    Route::get('workOrder-revert/{id}', 'TaskController@workOrderRevert');

    // Route::get('task-create', 'TaskController@taskCreate')->name('task.create');
    // Route::post('task-store', 'TaskController@taskStore')->name('task.store');
    Route::delete('task-delete/{id}', 'TaskController@destroy')->name('task.delete');
    // Route::get('task-edit/{id}', 'TaskController@edit')->name('task.edit');
    // Route::post('task-update/{id}', 'TaskController@update')->name('task.update');
    Route::get('schedule-edit/{id}/{completed?}', 'TaskController@scheduleEdit')->name('schedule.edit');
    Route::post('schedule-task-store/{id}', 'TaskController@ScheduleTaskStore')->name('schedule.task.store');
    Route::get('task-complete/{id}', 'TaskController@taskComplete')->name('task.complete');
    Route::get('task-incomplete/{id}', 'TaskController@taskInComplete')->name('task.incomplete');
    Route::get('task-unschedule/{id}', 'TaskController@taskUnschedule')->name('task.unschedule');
    Route::resource('items', 'ItemController');

    //Route::get('issue', 'IssueController@index')->name('issue.index');
    //Route::get('issue-create', 'IssueController@create')->name('issue.create');
    //Route::post('issue-store', 'IssueController@store')->name('issue.store');
    //Route::delete('issue-delete/{id}', 'IssueController@destroy')->name('issue.delete');
    //Route::get('issue-edit/{id}', 'IssueController@edit')->name('issue.edit');
    //Route::patch('issue-update/{id}', 'IssueController@update')->name('issue.update');

    Route::get('month-numbers', 'TaskController@getWeekNumbers')->name('get.month.numbers');

    Route::get('days-date', 'TaskController@decideComingDateAndNumberOfDays')->name('get.days.date');

    Route::get('reject-ticket', 'CommonController@ticketRejected')->name('ticket.reject');

    Route::get('generate-work-order', 'TaskController@GenerateWorkOrder')->name('generate.work.order');
    Route::get('delete-contract-file/{id}', 'PropertyController@deleteContractFile');

    Route::get('contracts/index/{client_id?}', 'ContractsController@index')->name('contracts.index');
    Route::get('contracts/allcontracts', 'ContractsController@allContracts')->name('contracts.allcontracts'); 
    Route::get('contracts/create/{client_id?}', 'ContractsController@create')->name('contracts.create');
    Route::post('contracts/store/{client_id?}', 'ContractsController@store')->name('contracts.store');

    Route::get('contracts/edit/{client_id?}/{id?}', 'ContractsController@edit')->name('contracts.edit');
    Route::put('contracts/update/{client_id?}/{id?}', 'ContractsController@update')->name('contracts.update');

    Route::get('retrieve_doc/{envelope_id?}', 'ContractsController@retrieveDocument')->name('retrieve_document');
    Route::get('update_contract_statuses', 'ContractsController@updateContractStatuses')->name('update_contract_statuses');

    Route::get('lists/index/{issue_id}', 'ItemController@listsIndex')->name('lists.index');

    Route::get('lists/create/{issue_id}', 'ItemController@listsCreate')->name('lists.create');
    Route::get('load/issue-list/{issue_id}', 'ItemController@issuesList');
    Route::get('lists/edit/{issue_id}/{id}', 'ItemController@listsEdit')->name('lists.edit');
    Route::post('lists/store/{issue_id}', 'ItemController@listsStore')->name('lists.store');
    Route::patch('lists/update/{issue_id}/{id}', 'ItemController@listsUpdate')->name('lists.update');
    Route::put('save-contract_tasks', 'ContractsController@contractTaskStore');
    Route::put('edit-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskUpdate');
    Route::put('add-images-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskAddImages');

    Route::get('contract_task/edit/{id}', 'ContractsController@contractTaskEdit');
    Route::get('contract_task/upload_images/{id}', 'ContractsController@contractTaskUploadImages');
    Route::get('contract_task/all/{id}', 'ContractsController@getContractTask');
  
    Route::get('to-words/{value?}', 'ContractsController@toWords');
});

Route::post('changePassword', 'Admin\UsersController@changePassword');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;

class Task extends Model implements Auditable
{
    use HasFactory, SoftDeletes, \OwenIt\Auditing\Auditable;

    protected $fillable = [
        'work_order',
        'property_id',
        'issue_id',
        'type',
        'description',
        'recurring_type',
        'escorted',
        'or_each_day',
        'week_day',
        'every_days',
        'schedule',
        'date_month', 
        'recurring_end_date',
        'is_active',
        'remaining_days',
        'scheduled_task',
        'created_by',
        'user_id',
        'client_id',
        'schedule_time',
    ];

    public function property()
    {
        return $this->belongsTo(Property::class);
    }
    public function workOrder()
    {
        return $this->belongsTo(WorkOrder::class);
    }

    public function issue()
    {
        return $this->belongsTo(Issue::class, 'issue_id', 'id')->orderBy('issue');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function client()
    {
        return $this->belongsTo(Client::class, 'client_id', 'id');
    }
}

resources/views/pages/task/create.blade.php
@extends('master')
@section('title', 'Task Create')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <h4 class="semi-bold text-center light-heading">{{ __('Create Work Order') }}</h4>
                    <div class="card-body">
                        <form method="POST" id="task-form" action="{{ route('admin.tasks.store') }}">
                            @include('pages.task.form')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
         $(function() {
            $('#task-form').validate({
                rules: {
                    property_id: {
                        required: true,
                    },
                    item: {
                        required: true,
                    },
                    date_month: {
                        required: true,
                    },
                    item_desc: {
                        required: true,
                    },

                    type: {
                        required: true,
                    },
                    recurring_type: {
                        required: true,
                    },

                    monthly_date_month: {
                        required: true,
                    },
                    week_day: {
                        required: false,
                    },
                    recurring_end_date: {
                        required: true,
                    },
                    annually_date_month: {
                        required: true,
                    },

                    annually_recurring_end_date: {
                        required: true,
                    },

                    every_days: {
                        required: true,
                    },
                    daily_recurring_end_date: {
                        required: true,
                    },
                    is_active: {
                        required: true,
                    },
                   
                },
                messages: {
                    red_box: {
                        maxlength: 'The white box must be empty'
                    }
                },
                submitHandler: function(form) {
                    form.submit();
                }

            });
        });
        $(document).ready(function() {

            $('.date_month').datepicker({
                autoclose: true,
                format: "mm-yyyy",
                startView: "months",
                minViewMode: "months"
            });

            $('.recurring_end_date').datepicker({
                autoclose: true,
                format: "mm-dd-yyyy",
            });


            $('input[type=radio][name=type]').change(function() {
                if (this.value === 'one_time') {
                    $('#oneTimeType').show();
                    $('#recurringType').hide();
                    $('#monthly').hide();
                    $('#daily').hide();
                    $('#annually').hide();
                }

                if (this.value === 'recurring') {
                    $("select option").each(function() {
                        if ($(this).val() == "MONTHLY") {
                            $(this).attr("selected", "selected");
                        }
                    });
                    $('#oneTimeType').hide();
                    $('#recurringType').show();
                    $('#monthly').show();
                    $('#recurring_type').val(null).trigger('change');
                    $('#recurring_type').val('MONTHLY');
                    $('#recurring_type').trigger('change');
                }
            });

            $('#recurring_type').change(function() {

                if ($('#recurring_type').val() === 'MONTHLY') {
                    $('#monthly').show();
                    $('#daily').hide();
                    $('#annually').hide();
                }else if ($('#recurring_type').val() === 'DAILY') {
                    $('#monthly').hide();
                    $('#daily').show();
                    $('#annually').hide();
                }else {
                    $('#monthly').hide();
                    $('#daily').hide();
                    $('#annually').show();
                }
            });

            /*$('#monthly_date_month').change(function() {
                var month = $(this).val();

                if (month !== '') {
                    $.ajax({
                        url: "{{ route('admin.get.month.numbers') }}",
                        type: "GET",
                        data: {
                            "_token": "{{ csrf_token() }}",
                            "month": month
                        },
                        cache: false,
                        async: false,
                        success: function(data) {
                            var month = JSON.parse(data);
                            var i = 0;
                            var option = '<option value="">Select Week</option>';
                            var str = '';

                            while (i < month.length) {
                                if (i === 0) {
                                    str = 'First';
                                }

                                if (i === 1) {
                                    str = 'Second';
                                }

                                if (i === 2) {
                                    str = 'Third';
                                }

                                if (i === 3) {
                                    str = 'Fourth';
                                }

                                if (i === 4) {
                                    str = 'Last';
                                }

                                option = option + '<option value="' + month[i] +
                                    '" @if ($task->or_each_day == "'+ month[i] +'") {{ 'selected' }} @endif>' +
                                    str + '</option>';

                                i++;
                            }
                            $('#or_each').html(option);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                }
            });*/

            $('#week_day').change(function() {
                var monthYear = $('#monthly_date_month').val();
                var week = $('#or_each').val();
                var weekDay = $(this).val();

                if (monthYear !== '' && week !== '' && weekDay !== '') {
                    $.ajax({
                        url: "{{ route('admin.get.days.date') }}",
                        type: "GET",
                        data: {
                            "_token": "{{ csrf_token() }}",
                            "monthYear": monthYear,
                            "week": week,
                            "weekDay": weekDay,
                        },
                        cache: false,
                        async: false,
                        success: function(data) {
                            var result = JSON.parse(data);

                            console.log(result);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                }
            });
            
            $('#property_id').change(function() {
                var propertyId = $(this).val();

                if (propertyId != '') {

                    $.ajax({
                        url: "{{ route('admin.generate.work.order') }}",
                        type: "GET",
                        data: {
                            "_token": "{{ csrf_token() }}",
                            "property_id": propertyId,

                        },
                        cache: false,
                        async: false,
                        dataType: 'JSON',
                        success: function(data) {
//                            alert(data.work_order);
                            var result = data.work_order;
                            if (result == 'Not-Assigned-client') {
                                $('#work_order').val('Please! Assign property to a client.');
                                $('#save-form').attr('disabled', true);
                            } else {
                                $('#save-form').attr('disabled', false);
                                $('#work_order').val(result);
                            }
                            $('#client_id').val(data.client_id);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                }
            });
         isSpecific('#date_day');

        });
         function isSpecific($this){
            $(".is-specific-fields").addClass('d-none');
            $(".is-specific-fields-"+$($this).val()).removeClass('d-none');
        }
    </script>
@endsection

resources/views/pages/task/filter.blade.php
<div class="container mb-5">
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
            <label for="property_id" class="font-weight-bold">Property</label>
            <select name="property_id" id="property_id" class="form-control">
                <option value="">Select Property</option>
                @foreach ($properties as $property)
                    <option value="{{ $property->id }}">{{ $property->property_name }}</option>
                @endforeach
            </select>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <label for="" class="font-weight-bold">From Date</label>
            <input type="text" name="from_date" id="from_date" class="form-control" autocomplete="off"/>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <label for="" class="font-weight-bold">To Date</label>
            <input type="text" name="to_date" id="to_date" class="form-control" autocomplete="off"/>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <span class="font-weight-bold">Contact Name:</span>    
            <span class="contact_name"></span>    
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <span class="font-weight-bold">Phone:</span>
            <span class="phone"></span>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
            <span class="font-weight-bold">Email:</span>
            <span class="email"></span>
        </div>
    </div>
</div>

resources/views/pages/task/index.blade.php
@extends('master')
@section('title', 'schedular')
@section('content')

<div class="container-fluid">
    @if($client)
    <div class="card">
        <!-- Start of Extra Information-->
        <h4 class="bold" style="padding:0px 10px;font-size:14px;"><a class="toggler" href="javascript:;"
                                                                     onClick="toggleSearch('client-info', '0', this)">{{ __('Client Information') }} <span
                    class="text-danger">*</span><span class="pull-right"><i class="fa fa-chevron-down"></i></span></a></h4>

        <div class="card-body" style="display:none"
             id="client-info">
            @include('contracts.partials.client_information')

        </div>
    </div>

    <div class="card">
        <!-- Start of Extra Information-->
        <h4 class="bold" style="padding:0px 10px;font-size:14px;"><a class="toggler" href="javascript:;"
                                                                     onClick="toggleSearch('detailfields', '0', this)">{{ __('Property Information') }} <span
                    class="text-danger">*</span><span class="pull-right"><i class="fa fa-chevron-down"></i></span></a></h4>

        <div class="card-body" style="display:none"
             id="detailfields">
            @include('contracts.partials.property_information')
        </div>
    </div>
    @include('contracts.partials.contract_info')
    @endif
    @if(!$client || request()->has('search'))
        @include('pages.task.task_search')
    @endif
    @if (Session::has('message'))
    <div class="row">
        <div class="container text-center">
            <div class="alert alert-success message">
                {{ Session::get('message') }}
            </div>
        </div>
    </div>
    @endif
    @can('workOrder-create')
    <!--<a href="{{ route('admin.tasks.create') }}" class="btn btn-primary float-right mb-2" role="button">Create Work Order</a>-->
    @endcan
    <div class="clearfix"></div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card text-center">
                <!-- navigation in .card-header -->
                <div class="card-header">
                    <?php
                    $isFilterApplied = '';
                    if (request()->all()) {
                        $filters = request()->all();
                        $isFilterApplied = '?' . http_build_query($filters, '', '&');
                    }
                    ?>

                    <ul class="nav nav-tabs nav-fill">

                        <li class="nav-item">
                            <a id="scheduled-link" class='nav-link pill1 @if($type=="SCHEDULED") active @endif' 
                            
                               href="{{ route('admin.task.index', ['type'=> 'SCHEDULED']).$isFilterApplied }}">Maintenance Scheduled</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link pill2 @if($type=='NOT_SCHEDULED') active @endif" 
                               
                               href="{{ route('admin.task.index', ['type'=> 'NOT_SCHEDULED']).$isFilterApplied }}">Maintenance Not Scheduled</a>
                        </li>

                        <li class="nav-item">
                            <a 
                               class="nav-link pill3 @if($type=='COMPLETED') active @endif"
                               href="{{ route('admin.task.index', ['type'=> 'COMPLETED']).$isFilterApplied }}">Maintenance Completed</a>
                        </li>
                    </ul>
                </div>

                <!-- .card-body.tab-content  -->
                <div class="card-body tab-content">
                    <div class="tab-pane fade show active" id="home">
                        @include('contracts.partials.all_tasks')
                    </div>
                </div><!-- /.card-body -->
            </div><!-- /.card -->
        </div>
    </div>
    <div class="row">
    <div class="col-sm-12">
        <div class="card text-center">
            <!-- navigation in .card-header -->
            <div class="card-header all-task-container">
                @if($client)
                    @include('contracts.partials.assign_tasks')
                @endif
            </div>
        </div>
    </div>    
    </div>
</div>

<script>
    $(document).ready(function () {
        //getTask('#scheduled-link');
    });
    function paginatedTasks($this) {
        var href = $($this).attr('href');
        $('#home').load(href);
        return false;
    }
    function getTask($this) {
        $('.nav-link').removeClass('active');
        $($this).addClass('active');
        var href = $($this).attr('href');
        $('#home').load(href);
        return false;
    }
    function editTask($id) {
        $('.all-task-container').load("{{ url('backend/contract_task/edit') }}/" + $id, function () {
            $('.d-datepicker').datepicker({
                autoclose: true
            });
            $('.d-select2').select2();
        });
    }
    function taskUploadImages($id) {
        $('.holder').html('');
        $('.all-task-container').load("{{ url('backend/contract_task/upload_images') }}/" + $id, function () {
            $('.d-datepicker').datepicker({
                autoclose: true
            });
            $('.d-select2').select2();
        });
    }

    function getIssuesList() {
        resetTasks();
    }
    function resetTasks() {
        var issue_id = $('#issue_id').val();
        $('#issues-list-container').load('{{url("backend/load/issue-list/")}}/' + issue_id, function () {
            $('#selected-issues-container').html('');
        });
    }
    function moveBack($this) {
        $($this).attr('onclick', 'moveThis(this)');
        $($this).addClass('not-selected');
        $($this).appendTo('.issues-list-container');
        $($this).find('.issue-list-id').attr('disabled', true);
    }
    function moveThis($this) {
        $($this).attr('onclick', 'moveBack(this)');
        $($this).removeClass('not-selected');
        $($this).find('.issue-list-id').removeAttr('disabled');
        $($this).appendTo('#selected-issues-container');
    }
    function toggleFields() {
        $('.dd').addClass('d-none');
        $('.d-' + $('#type').val()).removeClass('d-none');
    }
    function removeIssue($this) {
        if ($('.other-task').length == 1) {
            alert('Last Element can not be deleted. You may left empty.');
            return false;

        }
        $($this).parents('.other-task').remove();
    }  

        $('.client').change(function () {

            if ($(this).val() !== '') {
                $('.contact_name_label').show();
                $('.phone_label').show();
                $('.email_label').show();
                $('.address_label').show();
            } else {
                $('.contact_name_label').hide();
                $('.phone_label').hide();
                $('.email_label').hide();
                $('.address_label').hide();
            }
        });


        $('#client_id').change(function () {

            var client_id = $(this).val();

            if (client_id !== '') {
                $.ajax({
                    url: "{{ route('admin.get.client.info') }}",
                    type: "GET",
                    data: {
                        "_token": "{{ csrf_token() }}",
                        "client_id": client_id
                    },
                    cache: false,
                    async: false,
                    success: function (data) {
                            console.log(data);
                        var data = JSON.parse(data);

                        $('.contact_name').html(data.first_name);
                        $('.phone').html(data.phone_one);
                        $('.email').html(data.email);
                        $('.address').html(data.address_one);

                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            } else {
                $('.contact_name').text('');
                $('.phone').text('');
                $('.email').text('');
                $('.address').text('');
            }
        });      
</script>
@endsection

resources/views/pages/task/schedule.blade.php
@extends('master')
@section('title', 'Task Schedule')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <h4 class="semi-bold text-center light-heading">{{ __('Schedule Work Order') }}</h4>
                    <div class="card-body">
                        <form method="POST" id="task-form" action="{{ route('admin.schedule.task.store', $task->id) }}">
                            @include('pages.task.scheduleForm')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function() {
$('#task-form').validate();
            $('.date_month').datepicker({
                autoclose: true,
                format: "mm-yyyy",
                startView: "months",
                minViewMode: "months"
            });

            $('.recurring_end_date').datepicker({
                autoclose: true,
                format: "mm-dd-yyyy",
            });
        });
    </script>
@endsection