routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('route:clear');
    dd(Artisan::output());
});

// Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
// Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
// Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
// Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
// Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
// Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');
// Route::post('/set-password', 'CommonController@changePassword')->name('set-password');
//Before authentication
Route::group(['middleware' => 'beforeAuth'], function () {
    Route::get('/login', 'Admin\UsersController@login');
    Route::get('/backend', 'Admin\UsersController@login');
    Route::get('backend/login', 'Admin\UsersController@login')->name('backend.login');
    Route::get('backend/forgotPassword', 'Admin\UsersController@recoverPassword');
    Route::get('backend/resetPassword/{token}', 'Admin\UsersController@resetPassword');


    Route::post('login', 'Admin\UsersController@login');
    Route::post('recoverPassword', 'Admin\UsersController@recoverPassword');

    //client routes
    Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
    Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
    Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
    Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
    Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
    Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');

    Route::post('/set-password', 'CommonController@changePassword')->name('set-password');

    Route::get('change-password', 'CommonController@changeClientPassword');
    Route::post('changeClientOldPassword', 'CommonController@changeClientPassword');

    Route::get('resetPasswordClient/{token}', 'CommonController@resetPassword');
    Route::get('client-forgotPassword', 'CommonController@recoverPassword');
    Route::post('client-recoverPassword', 'CommonController@recoverPassword');

    Route::get('client-generate-work-order', 'TaskController@GenerateWorkOrder')->name('client.generate.work.order');
});


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function () {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list', 'Admin\UsersController@index')->name('users.index');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard/{type?}', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');

    Route::resource('properties', 'PropertyController');
    Route::match(['get', 'post'], '/property-list', 'PropertyController@index')->name('property.index');

    Route::resource('clients', 'ClientController');
    Route::match(['get', 'post'], '/client-list', 'ClientController@index')->name('client.index');

    Route::resource('client_properties', 'ClientPropertyController');
    Route::match(['get', 'post'], '/client-property-list', 'ClientPropertyController@index')->name('client_properties.index');


    Route::resource('leads', 'LeadController');
    Route::get('/arcive-lead/{id?}', 'LeadController@archive_lead')->name('lead.archive');
    Route::match(['get', 'post'], '/lead-list', 'LeadController@index')->name('lead.index');


    // Route::get('tasks', 'TaskController@index')->name('task.index');
    // Route::post('tasks-check', 'TaskController@index')->name('task.check');
    Route::match(['get', 'post'], '/task-list/{type?}', 'TaskController@index')->name('task.index');
    Route::get('get-client', 'TaskController@getClientInfo')->name('get.client.info');
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/{id}/edit/{completed?}', 'TaskController@edit')->name('tasks.edit');
    Route::get('workOrder-revert/{id}', 'TaskController@workOrderRevert');

    // Route::get('task-create', 'TaskController@taskCreate')->name('task.create');
    // Route::post('task-store', 'TaskController@taskStore')->name('task.store');
    Route::delete('task-delete/{id}', 'TaskController@destroy')->name('task.delete');
    // Route::get('task-edit/{id}', 'TaskController@edit')->name('task.edit');
    // Route::post('task-update/{id}', 'TaskController@update')->name('task.update');
    Route::get('schedule-edit/{id}/{completed?}', 'TaskController@scheduleEdit')->name('schedule.edit');
    Route::post('schedule-task-store/{id}', 'TaskController@ScheduleTaskStore')->name('schedule.task.store');
    Route::get('task-complete/{id}', 'TaskController@taskComplete')->name('task.complete');
    Route::get('task-incomplete/{id}', 'TaskController@taskInComplete')->name('task.incomplete');
    Route::get('task-unschedule/{id}', 'TaskController@taskUnschedule')->name('task.unschedule');
    Route::resource('items', 'ItemController');

    //Route::get('issue', 'IssueController@index')->name('issue.index');
    //Route::get('issue-create', 'IssueController@create')->name('issue.create');
    //Route::post('issue-store', 'IssueController@store')->name('issue.store');
    //Route::delete('issue-delete/{id}', 'IssueController@destroy')->name('issue.delete');
    //Route::get('issue-edit/{id}', 'IssueController@edit')->name('issue.edit');
    //Route::patch('issue-update/{id}', 'IssueController@update')->name('issue.update');

    Route::get('month-numbers', 'TaskController@getWeekNumbers')->name('get.month.numbers');

    Route::get('days-date', 'TaskController@decideComingDateAndNumberOfDays')->name('get.days.date');

    Route::get('reject-ticket', 'CommonController@ticketRejected')->name('ticket.reject');

    Route::get('generate-work-order', 'TaskController@GenerateWorkOrder')->name('generate.work.order');
    Route::get('delete-contract-file/{id}', 'PropertyController@deleteContractFile');

    Route::get('contracts/index/{client_id?}', 'ContractsController@index')->name('contracts.index');
    Route::get('contracts/allcontracts', 'ContractsController@allContracts')->name('contracts.allcontracts'); 
    Route::get('contracts/create/{client_id?}', 'ContractsController@create')->name('contracts.create');
    Route::post('contracts/store/{client_id?}', 'ContractsController@store')->name('contracts.store');

    Route::get('contracts/edit/{client_id?}/{id?}', 'ContractsController@edit')->name('contracts.edit');
    Route::put('contracts/update/{client_id?}/{id?}', 'ContractsController@update')->name('contracts.update');

    Route::get('retrieve_doc/{envelope_id?}', 'ContractsController@retrieveDocument')->name('retrieve_document');
    Route::get('update_contract_statuses', 'ContractsController@updateContractStatuses')->name('update_contract_statuses');

    Route::get('lists/index/{issue_id}', 'ItemController@listsIndex')->name('lists.index');

    Route::get('lists/create/{issue_id}', 'ItemController@listsCreate')->name('lists.create');
    Route::get('load/issue-list/{issue_id}', 'ItemController@issuesList');
    Route::get('lists/edit/{issue_id}/{id}', 'ItemController@listsEdit')->name('lists.edit');
    Route::post('lists/store/{issue_id}', 'ItemController@listsStore')->name('lists.store');
    Route::patch('lists/update/{issue_id}/{id}', 'ItemController@listsUpdate')->name('lists.update');
    Route::put('save-contract_tasks', 'ContractsController@contractTaskStore');
    Route::put('edit-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskUpdate');
    Route::put('add-images-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskAddImages');

    Route::get('contract_task/edit/{id}', 'ContractsController@contractTaskEdit');
    Route::get('contract_task/upload_images/{id}', 'ContractsController@contractTaskUploadImages');
    Route::get('contract_task/all/{id}', 'ContractsController@getContractTask');
  
    Route::get('to-words/{value?}', 'ContractsController@toWords');
});

Route::post('changePassword', 'Admin\UsersController@changePassword');

resources/views/docusign.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Laravel Docusign Integration Example - ItSlutionStuff.com</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container">
  
    @if ($message = Session::get('success'))
      <div class="alert alert-success alert-block">
          <button type="button" class="close" data-dismiss="alert">×</button>    
          <strong>{{ $message }}</strong>
      </div>
    @endif
  
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Laravel Docusign Integration Example - ItSlutionStuff.com</h5>
      </div>
      <div class="card-body">
        <h5 class="card-title">Docusign Tutorial</h5>
  
        <p class="card-text">Click the button below to connect your application with Docusign</p>
  
        @if ($message = Session::get('success'))
            <a href="{{ route('docusign.sign') }}" class="btn btn-primary">Click to Sign Document</a>
        @else
            <a href="{{ route('connect.docusign') }}" class="btn btn-primary">Connect Docusign</a>
        @endif
          
      </div>
    </div>
  
  </div>
</body>
</html>

resources/views/footer.blade.php
<div class="ajax-loader" style="background:white;display:none;padding:10px;">
    <img src="{{asset('img/loading.gif')}}" style="display:block;margin:auto;" />
</div>

</div>
<!-- End of Content Container -->
</div>
<!-- END PAGE CONTENT -->
<!-- START COPYRIGHT -->
<!-- START CONTAINER FLUID -->
<!-- START CONTAINER FLUID -->
<div class=" container   container-fixed-lg footer">
          <div class="copyright sm-text-center">
            <p class="small no-margin pull-left sm-pull-reset">
                <span class="font-montserrat">Copyright ©2022. Developed By: <a target="_blank" href="https://cyberclouds.com/" style="text-decoration: none">Cyberclouds</a></span>.
              {{-- <span class="hint-text">All rights reserved. </span> --}}
            </p>
            {{--<p class="small no-margin pull-right sm-pull-reset">
              <a href="https://www.cyberclouds.com">Cyber Clouds</a> <span class="hint-text"> made with Love</span>
            </p>--}}
            <div class="clearfix"></div>
          </div>
        </div>
        <!-- END COPYRIGHT -->
      </div>
      <!-- END PAGE CONTENT WRAPPER -->
</div>
<!-- END PAGE CONTAINER -->

resources/views/header.blade.php
<div class="header p-r-0 bg-primary">
    <div class="header-inner header-md-height">
        <a href="#" class="btn-link toggle-sidebar d-lg-none pg pg-menu text-white" data-toggle="horizontal-menu"></a>
        <div class="">
            <div class="brand inline no-border d-sm-inline-block">
                
                    <img style="width: 175px;" src="{{ asset('logo.png') }}" alt="{{ config('app.name') }}"
                    data-src="{{ asset('logo.png') }}" data-src-retina="{{ asset('logo.png') }}"
                    class="img-fluid">                    
                
                  
            </div>
        </div>

        <div class="d-flex align-items-right">
            <h6 class="text-white text-left"><i class="fa fa-phone"></i> 813-628 8453</h6> &nbsp;&nbsp;
            <h6 class="text-white text-left"><i class="fa fa-envelope"></i> sam@stone-kraft.com</h6>&nbsp;&nbsp;
            <h6 class="text-white text-left"><i class="fa fa-map-pin"></i> 2402 S 50th St, Tampa , FL 33619</h6>
        </div>
        <div class="d-flex align-items-center">
            <!-- START User Info-->

            <div class="dropdown pull-right">
                <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false">
                    <div class="pull-left p-r-10 fs-14 font-heading d-lg-inline-block text-white">
                        <span class="semi-bold">Logged in as {{ Auth::user()->first_name }}</span>
                    </div>
                </button>
                <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
                    <!-- <a href="{{ url('/backend/user-profile') }}" class="dropdown-item"><i class="fa fa-user"></i> Profile</a> -->
                    <a href="{{ url('/') }}/backend/change-password" class="dropdown-item"><i
                            class="pg-settings_small"></i> Change Password</a>
                    <a href="javascript:"
                        onClick="event.preventDefault();document.getElementById('logout-form').submit()"
                        class="clearfix bg-master-lighter dropdown-item">
                        <form action="{{ route('admin.logout') }}" method="POST" style="display:none;" id="logout-form">
                            @csrf
                            @method('POST')
                        </form>
                        <span class="pull-left pr-2"><i class="pg-power"></i></span>
                        <span class="pull-left">Logout</span>
                        
                    </a>
                </div>
            </div>
            <!-- END User Info-->
        </div>
    </div>
    @auth
        <?php
        ?>
        <div class="bg-white">
            <div class="container">
                <div class="menu-bar header-sm-height" data-pages-init='horizontal-menu' data-hide-extra-li="">
                    <a href="#" class="btn-link toggle-sidebar d-lg-none pg pg-close" data-toggle="horizontal-menu">
                    </a>
                    <ul>
                        @if(count(Auth::user()->roles)==1 && in_array(14,Auth::user()->roles->pluck('id')->toArray()))
                        @else
                        <li class="@if(in_array('dashboard',Request::segments())) {{'active'}} @endif">
                            <a href="{{url('/')}}/backend/dashboard">Dashboard</a>
                        </li>
                        @endif
                        @canany(['user-list', 'role-list'])
                            <li class="@if (in_array('users', Request::segments()) || in_array('users-list', Request::segments()) || in_array('roles', Request::segments())) {{ 'active' }} @endif">
                                <a class="nav-link dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false" href="javascript:">Users</a>
                                <div class="dropdown-menu dropdown-menu-right profile-dropdown" role="menu">
                                    @can('user-list')
                                        <a class="nav-link" href="{{ route('admin.users.index') }}">Manage Users</a>
                                    @endcan
                                    @can('role-list')
                                        <a class="nav-link" href="{{ route('admin.roles.index') }}">Manage Roles</a>
                                    @endcan
                                </div>
                            </li>
                        @endcanany
                        <li class="@if(in_array('lead-list',Request::segments())) {{'active'}} @endif">
                            @can('lead-list')
                                <a href="{{ route('admin.lead.index') }}">Leads</a>
                            @endcan
                        </li>
                        <li class="@if(in_array('clients',Request::segments())) {{'active'}} @endif">
                            @can('client-list')
                                <a href="{{ route('admin.contracts.allcontracts') }}">Contracts</a>
                            @endcan
                        </li>
               

                        <li class="@if(in_array('task-list',Request::segments())) {{'active'}} @endif">
                            @can('workOrder-list')
                                <a href="{{ route('admin.task.index') }}">Work Order</a>
                            @endcan
                        </li>
<!--                        <li class="@if(in_array('contracts',Request::segments())) {{'active'}} @endif">
                                <a href="{{ route('admin.contracts.index') }}">Contracts</a>
                        </li>-->
                        <li class="@if(in_array('items',Request::segments())) {{'active'}} @endif">
                            @can('task-type-list')
                                <a href="{{ route('admin.items.index') }}">Item Types</a>
                            @endcan
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    @endauth
</div>

<div class="page-container ">
    <!-- START PAGE CONTENT WRAPPER -->
    <div class="page-content-wrapper ">
        <!-- START PAGE CONTENT -->
        <div class="content sm-gutter">
            <!-- START BREADCRUMBS -->
            <div class="bg-white">
                <div class="container">

                    <ol class="breadcrumb breadcrumb-alt">
                        <li class="breadcrumb-item"><a href="{{url('/')}}/backend/dashboard">Home</a></li>
                           
                        @if(isset($breadcrumbs))
                        @foreach($breadcrumbs as $breadcrumb)
                         <li class="breadcrumb-item"><a href="<?= $breadcrumb['url'] ?>"><?= $breadcrumb['title'] ?></a> </li>
                        @endforeach
                        @else
                            <?php
                        $link = URL::to('/');
                        ?>
                        @for($i = 1; $i <= count(Request::segments()); $i++)
                        @if($i < count(Request::segments()) & $i > 0)
                        <?php
                        if (Request::segment($i) == 'edit') {
                            continue;
                        }
                        if (is_numeric(Request::segment($i))) {
                            continue;
                        }
                        $link .= "/" . Request::segment($i);
                        if ($link != URL::to('/') . "/backend") {
                            if ($i != 3 && is_int(intval(ucwords(str_replace('-', ' ', Request::segment($i)))))) {
                                $s2 = str_replace('-', ' ', Request::segment($i));
                                ?>
                                <li class="breadcrumb-item"><a href="<?= $link ?>">{{ ucwords($s2)}}</a> </li>
                                <?php
                            }
                        }
                        ?>
                        @else  
                        <?php
                        $s2 = str_replace('_', ' ', str_replace('-', ' ', Request::segment($i)));
                        ?>
                        <li class="breadcrumb-item active"> {{  ucwords($s2) }}</li>
                        @endif
                        @endfor  
                        @endif
                    </ol>
                </div>
            </div>
            <!-- END BREADCRUMBS -->
           
                {{-- @include('partials.alerts') --}}

resources/views/login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <title>{{config('app.name','Content Management System')}} - @yield('title')</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="{{ asset('pages/css/themes/modern.css') }}" />
    <link rel="stylesheet" href="{{asset('login/css/style.css')}}">
    <link rel="stylesheet" href="{{asset('login/css/animate.css')}}">
    <link rel="stylesheet" href="{{ asset('validate-password/css/jquery.passwordRequirements.css') }}" />
 <style>
         .error {
    color: orange !important;
   }
    </style>
    </head>
    
    <body class="img js-fullheight">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center pr-4 pl-4">
                <div class="heading-section pt-2 pb-2 rounded border col-md-7 text-center mb-0" style="background-color: rgba(0,0, 0, 0.7);">
                    <div class="row">
                        <div class="col-md-7">
                            <img src="{{ asset('logo.png')}}" width="210px"/>
                        </div>
                        <div class="col-md-5">
                            <h6 class="text-white text-left"><i class="fa fa-phone"></i> 813-628 8453</h6>
                            <h6 class="text-white text-left"><i class="fa fa-envelope"></i> sam@stone-kraft.com</h6>
                        </div>
                    </div>
                </div>
            </div>
             @yield('content')
        </div>
    </section>

    <script src="{{asset('login/js/jquery.min.js')}}"></script>
  <script src="{{asset('login/js/popper.js')}}"></script>
  <script src="{{asset('login/js/bootstrap.min.js')}}"></script>
  <script src="{{asset('login/js/main.js')}}"></script>
   <script src="{{asset('plugins/jquery-validation/js/jquery.validate.min.js')}}" type="text/javascript"></script>
        <!-- END VENDOR JS -->
        <script src="{{ asset('validate-password/js/jquery.passwordRequirements.js') }}"></script>

        <script src="{{asset('pages/js/pages.min.js')}}"></script>
        <script>
function redMustEmpty() {
    if ($('#redField').val().length > 0) {
        return false;
    }
}
$(function ()
{
    $(".pr-password").passwordRequirements();
    $('#form-login').validate({
        rules: {
            email: {
                required: true,
                email: true
            },
            password: {
                required: true,
                minlength: 8
            },
            red_box: {
                maxlength: 0
            },
            green_box: {
                required: true
            }
        },
        messages: {
            red_box: {
                maxlength: 'The white box must be empty'
            }
        },
        submitHandler: function (form) {
            $("#submitForm").html("Please wait...").attr('disabled', true);
            form.submit();
        }

    });





    $('#form-resetpass').validate({
        rules: {
            password: {
                required: true,
                pwcheck: true,
                minlength: 8
            },
            password_confirmation: {
                required: true,
                equalTo: "#password"
            }
        },
        message: {
            password: {
                required: "Password Required",
                pwcheck: "Password Week",
                minlength: "min 8 Char"
            }
        },
        submitHandler: function (form) {
            $("#submitForm").html("Please wait...").attr('disabled', true);
            form.submit();
        }

    });
    $.validator.addMethod("pwcheck", function (value) {

        return /^[a-zA-Z0-9!@#$%^&*()_=\[\]{};':"\\|,.<>\/?+-]+$/.test(value)
                && /[a-z]/.test(value) // has a lowercase letter
                && /\d/.test(value)//has a digit
                && /[!@#$%^&*()_=\[\]{};':"\\|,.<>\/?+-]/.test(value)// has a special character
    }, "Must consist  lowercase letter, number and special characters");

});
        </script>

    </body>
</html>

resources/views/myPDF.blade.php
{!! $html !!}