routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('route:clear');
    dd(Artisan::output());
});

// Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
// Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
// Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
// Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
// Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
// Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');
// Route::post('/set-password', 'CommonController@changePassword')->name('set-password');
//Before authentication
Route::group(['middleware' => 'beforeAuth'], function () {
    Route::get('/login', 'Admin\UsersController@login');
    Route::get('/backend', 'Admin\UsersController@login');
    Route::get('backend/login', 'Admin\UsersController@login')->name('backend.login');
    Route::get('backend/forgotPassword', 'Admin\UsersController@recoverPassword');
    Route::get('backend/resetPassword/{token}', 'Admin\UsersController@resetPassword');


    Route::post('login', 'Admin\UsersController@login');
    Route::post('recoverPassword', 'Admin\UsersController@recoverPassword');

    //client routes
    Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
    Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
    Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
    Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
    Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
    Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');

    Route::post('/set-password', 'CommonController@changePassword')->name('set-password');

    Route::get('change-password', 'CommonController@changeClientPassword');
    Route::post('changeClientOldPassword', 'CommonController@changeClientPassword');

    Route::get('resetPasswordClient/{token}', 'CommonController@resetPassword');
    Route::get('client-forgotPassword', 'CommonController@recoverPassword');
    Route::post('client-recoverPassword', 'CommonController@recoverPassword');

    Route::get('client-generate-work-order', 'TaskController@GenerateWorkOrder')->name('client.generate.work.order');
});


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function () {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list', 'Admin\UsersController@index')->name('users.index');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard/{type?}', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');

    Route::resource('properties', 'PropertyController');
    Route::match(['get', 'post'], '/property-list', 'PropertyController@index')->name('property.index');

    Route::resource('clients', 'ClientController');
    Route::match(['get', 'post'], '/client-list', 'ClientController@index')->name('client.index');

    Route::resource('client_properties', 'ClientPropertyController');
    Route::match(['get', 'post'], '/client-property-list', 'ClientPropertyController@index')->name('client_properties.index');


    Route::resource('leads', 'LeadController');
    Route::get('/arcive-lead/{id?}', 'LeadController@archive_lead')->name('lead.archive');
    Route::match(['get', 'post'], '/lead-list', 'LeadController@index')->name('lead.index');


    // Route::get('tasks', 'TaskController@index')->name('task.index');
    // Route::post('tasks-check', 'TaskController@index')->name('task.check');
    Route::match(['get', 'post'], '/task-list/{type?}', 'TaskController@index')->name('task.index');
    Route::get('get-client', 'TaskController@getClientInfo')->name('get.client.info');
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/{id}/edit/{completed?}', 'TaskController@edit')->name('tasks.edit');
    Route::get('workOrder-revert/{id}', 'TaskController@workOrderRevert');

    // Route::get('task-create', 'TaskController@taskCreate')->name('task.create');
    // Route::post('task-store', 'TaskController@taskStore')->name('task.store');
    Route::delete('task-delete/{id}', 'TaskController@destroy')->name('task.delete');
    // Route::get('task-edit/{id}', 'TaskController@edit')->name('task.edit');
    // Route::post('task-update/{id}', 'TaskController@update')->name('task.update');
    Route::get('schedule-edit/{id}/{completed?}', 'TaskController@scheduleEdit')->name('schedule.edit');
    Route::post('schedule-task-store/{id}', 'TaskController@ScheduleTaskStore')->name('schedule.task.store');
    Route::get('task-complete/{id}', 'TaskController@taskComplete')->name('task.complete');
    Route::get('task-incomplete/{id}', 'TaskController@taskInComplete')->name('task.incomplete');
    Route::get('task-unschedule/{id}', 'TaskController@taskUnschedule')->name('task.unschedule');
    Route::resource('items', 'ItemController');

    //Route::get('issue', 'IssueController@index')->name('issue.index');
    //Route::get('issue-create', 'IssueController@create')->name('issue.create');
    //Route::post('issue-store', 'IssueController@store')->name('issue.store');
    //Route::delete('issue-delete/{id}', 'IssueController@destroy')->name('issue.delete');
    //Route::get('issue-edit/{id}', 'IssueController@edit')->name('issue.edit');
    //Route::patch('issue-update/{id}', 'IssueController@update')->name('issue.update');

    Route::get('month-numbers', 'TaskController@getWeekNumbers')->name('get.month.numbers');

    Route::get('days-date', 'TaskController@decideComingDateAndNumberOfDays')->name('get.days.date');

    Route::get('reject-ticket', 'CommonController@ticketRejected')->name('ticket.reject');

    Route::get('generate-work-order', 'TaskController@GenerateWorkOrder')->name('generate.work.order');
    Route::get('delete-contract-file/{id}', 'PropertyController@deleteContractFile');

    Route::get('contracts/index/{client_id?}', 'ContractsController@index')->name('contracts.index');
    Route::get('contracts/allcontracts', 'ContractsController@allContracts')->name('contracts.allcontracts'); 
    Route::get('contracts/create/{client_id?}', 'ContractsController@create')->name('contracts.create');
    Route::post('contracts/store/{client_id?}', 'ContractsController@store')->name('contracts.store');

    Route::get('contracts/edit/{client_id?}/{id?}', 'ContractsController@edit')->name('contracts.edit');
    Route::put('contracts/update/{client_id?}/{id?}', 'ContractsController@update')->name('contracts.update');

    Route::get('retrieve_doc/{envelope_id?}', 'ContractsController@retrieveDocument')->name('retrieve_document');
    Route::get('update_contract_statuses', 'ContractsController@updateContractStatuses')->name('update_contract_statuses');

    Route::get('lists/index/{issue_id}', 'ItemController@listsIndex')->name('lists.index');

    Route::get('lists/create/{issue_id}', 'ItemController@listsCreate')->name('lists.create');
    Route::get('load/issue-list/{issue_id}', 'ItemController@issuesList');
    Route::get('lists/edit/{issue_id}/{id}', 'ItemController@listsEdit')->name('lists.edit');
    Route::post('lists/store/{issue_id}', 'ItemController@listsStore')->name('lists.store');
    Route::patch('lists/update/{issue_id}/{id}', 'ItemController@listsUpdate')->name('lists.update');
    Route::put('save-contract_tasks', 'ContractsController@contractTaskStore');
    Route::put('edit-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskUpdate');
    Route::put('add-images-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskAddImages');

    Route::get('contract_task/edit/{id}', 'ContractsController@contractTaskEdit');
    Route::get('contract_task/upload_images/{id}', 'ContractsController@contractTaskUploadImages');
    Route::get('contract_task/all/{id}', 'ContractsController@getContractTask');
  
    Route::get('to-words/{value?}', 'ContractsController@toWords');
});

Route::post('changePassword', 'Admin\UsersController@changePassword');

app/Models/Contract.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contract extends Model {

    use HasFactory;

    protected $guarded = [];

    public function client() {
        return $this->belongsTo(Client::class);
    }
    public function contract_tasks() {
        return $this->hasMany(ContractTask::class);
    }
    public function contract_works() {
        return $this->hasMany(ContractWork::class);
    }

}

resources/views/contracts/create.blade.php
@extends('master')
@section('title', 'Contract Create')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <h4 class="semi-bold text-center light-heading">{{ __('Create Contract - '.$client->first_name.' '.$client->last_name) }}</h4>

                    <div class="card-body">
                        <form method="POST" id="client-form" action="{{ route('admin.contracts.store',request()->client_id) }}">
                            @include('contracts.form')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/contracts/edit.blade.php
@extends('master')
@section('title', 'Contract Edit')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <h4 class="semi-bold text-center light-heading">
                    {{ __('Edit Contract - '.$client->first_name.' '.$client->last_name) }}
                </h4>
                <div class="card-body">
                    <form method="POST" id="client-form" action="{{ route('admin.contracts.update',[request()->client_id,request()->id]) }}">
                        @method('put')
                        @include('contracts.form')
                    </form>
                    @if($contract->status == 1)
                    <div class="card">
                        <!-- Start of Extra Information-->
                        <h4 class="bold" style="padding:0px 10px;font-size:14px;">
                            <a class="toggler" href="javascript:;"
                               onClick="toggleSearch('task-info', '0', this)">{{ __('Task Information') }} <span
                                    class="text-danger">*</span><span class="pull-right"><i class="fa fa-chevron-up"></i></span></a></h4>
                        <div class="card-body" style="display:block" id="task-info">
                            <div class="row" style="display:block" id="task-info">
                                <div class="col-lg-6">
                                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                                        <li class="nav-item flex-grow-1">
                                            <a onclick="getTask()" class="text-center nav-link active btn-block" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">All/Assigned Tasks</a>
                                        </li>
                                        <li class="nav-item flex-grow-1 te">
                                            <a  class="text-center nav-link btn-block" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Create Task</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="tab-content" id="myTabContent">
                                <!--include('contracts.partials.all_tasks')-->
                                <div class="tab-pane pt-3 fade show active all-task-container" id="home" role="tabpanel" aria-labelledby="home-tab">
                                    @include('contracts.partials.all_tasks')
                                </div>
                                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                    @include('contracts.partials.assign_tasks')
                                </div>
                            </div>
                        </div>
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
<script>
    function cloneTasks() {
        var $ele = $('.other-task:last').clone();
        $ele.find('input,textarea').val('');
        $ele.appendTo('.other-task-container');
    }
    $(document).ready(function () {
        //getTask();
    });
    function paginatedTasks($this) {
        var href = $($this).attr('href');
        $('#home').load(href);
        return false;
    }
    function getTask() {
        //$('#home').load('{{ url("backend/contract_task/all/".request()->id) }}');
    }
    function editTask($id) {
        $('.all-task-container').load("{{ url('backend/contract_task/edit') }}/" + $id, function () {
            $('.d-datepicker').datepicker({
                autoclose: true
            });
            $('.d-select2').select2();
        });
    }
</script>
@endsection

resources/views/contracts/form.blade.php
@csrf
<div class="card">
    <!-- Start of Extra Information-->
    <h4 class="bold" style="padding:0px 10px;font-size:14px;"><a class="toggler" href="javascript:;"
                                                                 onClick="toggleSearch('client-info', '0', this)">{{ __('Client Information') }} <span
                class="text-danger">*</span><span class="pull-right"><i class="fa fa-chevron-down"></i></span></a></h4>

    <div class="card-body" style="display:none"
         id="client-info">
        @include('contracts.partials.client_information')

    </div>
</div>


<div class="card">
    <!-- Start of Extra Information-->
    <h4 class="bold" style="padding:0px 10px;font-size:14px;"><a class="toggler" href="javascript:;"
                                                                 onClick="toggleSearch('additionalsigners', '0', this)">{{ __('Additional Signers') }} <span class="pull-right"><i class="fa fa-chevron-down"></i></span></a></h4>

    <div class="card-body" style="display:none"
         id="additionalsigners">
        @include('contracts.partials.additional_signers')
    </div>
</div>
<div class="card">
    <!-- Start of Extra Information-->
    <h4 class="bold" style="padding:0px 10px;font-size:14px;"><a class="toggler" href="javascript:;"
                                                                 onClick="toggleSearch('detailfields', '0', this)">{{ __('Property Information') }} <span
                class="text-danger">*</span><span class="pull-right"><i class="fa fa-chevron-down"></i></span></a></h4>

    <div class="card-body" style="display:none"
         id="detailfields">
        @include('contracts.partials.property_information')
    </div>
</div>
        @include('contracts.partials.contract_info')


<script>
    $(function () {
        $('#client-form').validate();
        //$('#client-info, #detailfields').find('input,select').attr('disabled', 'true');
        //$('#client-info, #detailfields').find('input, select').parent('div').addClass('disabled');
//        toggleFields();
        getIssuesList();
    });

    function getIssuesList() {
        resetTasks();
    }
    function resetTasks() {
        var issue_id = $('#issue_id').val();
        $('#issues-list-container').load('{{url("backend/load/issue-list/")}}/' + issue_id, function () {
            $('#selected-issues-container').html('');
        });
    }
    function moveBack($this) {
        $($this).attr('onclick', 'moveThis(this)');
        $($this).addClass('not-selected');
        $($this).appendTo('.issues-list-container');
        $($this).find('.issue-list-id').attr('disabled', true);
    }
    function moveThis($this) {
        $($this).attr('onclick', 'moveBack(this)');
        $($this).removeClass('not-selected');
        $($this).find('.issue-list-id').removeAttr('disabled');
        $($this).appendTo('#selected-issues-container');
    }
    function toggleFields() {
        $('.dd').addClass('d-none');
        $('.d-' + $('#type').val()).removeClass('d-none');
    }
    function removeIssue($this) {
        if ($('.other-task').length == 1) {
            alert('Last Element can not be deleted. You may left empty.');
            return false;

        }
        $($this).parents('.other-task').remove();
    }
</script>

resources/views/contracts/index.blade.php
@extends('master')
@section('title','Contracts')
@section('content')
<div class="container-fluid">
        @if (Session::has('message'))
            <div class="row">
                <div class="container text-center">
                    <div class="alert alert-success message">
                        {{ Session::get('message') }}
                    </div>
                </div>
            </div>
        @endif
    <h1 class="float-left">Contracts List</h1>
    @include('contracts.search_form')
    <!--
    <div class="pull-left">
    
		<i style="padding: 1px 9px;" data-toggle="tooltip" data-placement="top" title="" class="rounded-circle bg-primary ml-2 mr-2" data-original-title="Active"></i>
		<b>Active </b>
		
		<i style="padding: 1px 9px;" class="rounded-circle bg-danger ml-2 mr-2" data-toggle="tooltip" data-placement="top" title="" data-original-title="Inactive"></i>
		<b>Inactive</b>
	</div>
    -->
    @can('client-create')
    <!--
    <a href="{{ route('admin.contracts.create',request()->client_id) }}" class="btn btn-primary float-right" role="button">Create Contract</a>
    -->
    @endcan	
    <div class="clearfix"></div>
</div>
@include('contracts.list')    

@include('partials.loadmorejs')
<script>
    $(document).ready(function() {
        setTimeout(() => {
            $('.message').fadeOut('slow');
        }, 3000);
    });
</script>
@endsection

resources/views/contracts/list.blade.php
@php
$client_label2 = 'Price';
$client_label3 = 'SQ FT';
$client_label4 = 'Deposit';
$client_label5 = 'Balance';
$client_label6 = 'Template Date';
$client_label7 = 'Installation Date';
$client_label8 = 'Client';
$client_label9 = 'Contract Status';
$client_label10 = 'Action';
@endphp
<div class="container grid-wrapper p-3 mt-2">
    <div class="grid-header">
        <div class="row d-none d-md-flex mb-md-2 p-md-1">
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label2 }}</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label3 }}</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label4 }}</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label5 }}</h4>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label6 }}</h4>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label7 }}</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label8 }}</h4>
            </div>
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label9 }}</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $client_label10 }}</h4>
            </div>
        </div>
    </div>
    <div class="grid-body">
        @foreach ($clients as $client)
            @php
                $active = '<i style="" class="rounded-circle bg-primary" data-toggle="tooltip" data-placement="top" title=""></i>';
                $inactive = '<i style="" class="rounded-circle bg-danger" data-toggle="tooltip" data-placement="top" title=""></i>';
            @endphp
            <div class="row mb-md-0 p-md-1 mb-3 p-1">
                
                <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label2 }}</h4>
                    <p class="m-0 p-1">{{ $client->contract_price }}</p>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label3 }}</h4>
                    <p class="m-0 p-1">{{ $client->sq_ft }}</p>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label4 }}</h4>
                    <p class="m-0 p-1">{{ $client->deposit }}</p>
                </div>
               
                <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label5 }}</h4>
                    <p class="m-0 p-1">{{ $client->balance }}</p>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label6 }}</h4>
                    <p class="m-0 p-1">{{ formatDate($client->date_of_template,'u') }}</p>
                </div>
               
                <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label7 }}</h4>
                    <p class="m-0 p-1">{{ formatDate($client->date_of_installation,'u') }}</p>
                </div>
                
                <div class="col-1 col-sm-1 col-md-1">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label8 }}</h4>
                    <p class="m-0 p-1">{{ $client->client->first_name }} {{ $client->client->last_name }}</p>
                </div>
                <div class="col-2 col-sm-2 col-md-2">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label8 }}</h4>
                    @if($client->status == 0)
                        <span class="badge badge-warning">Pending</span>
                    @else
                        <a  target="_blank" class="badge badge-success" href="{{ route('admin.retrieve_document',$client->envelope_id) }}">View Contract</a>
                    @endif
                </div>
                <div class="col-1 col-sm-1 col-md-1">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $client_label9 }}</h4>
                    <br class="d-none d-md-none d-sm-block " />
                   
                    @can('client-edit')
                        <a href="{{route('admin.contracts.edit',[$client->client_id,$client->id])}}"
                            class="btn btn-primary mr-1 pt-1 pb-1 pl-2 pr-2" role="button">
                            Edit</a>
                    @endcan
                
                </div>
            </div> <!-- End of ROW -->
        @endforeach
    </div>
</div>

{{ $clients->links() }}

resources/views/contracts/search_form.blade.php
<div class="clearfix"></div>
<div class="row ">
    <div class="col-md-12">
        <div class="card">
            <h4 class="bold" style="padding:0px 10px;font-size:18px;"><a class="toggler" href="#"
                    onClick="toggleSearch('searchfields')">{{ __('Advanced Search') }}<span class="pull-right"><i
                            class="fa fa-chevron-down"></i></span></a></h4>
            <?php
            $display = 'display:none;';
            ?>
            <div class="card-body" style="{{ $display }}" id="searchfields">
                <form method="Post" id="searchform" accept-charset="utf-8"
                    action="{{ route('admin.client.index') }}">
                    @csrf
                    <div class="row">
                        <input type="hidden" name="sort_field" class="sort_field" value="">
                        <input type="hidden" name="sort_order" class="sort_order" value="">
                        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <input autofocus="" type="text" name="first_name" value="" class=" searchfield form-control"
                                placeholder="First Name" id="first_name">
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <input autofocus="" type="text" name="last_name" value="" class=" searchfield form-control"
                                placeholder="Last Name" id="last_name">
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <input autofocus="" type="text" name="email" value="" class=" searchfield form-control"
                                placeholder="email" id="email">
                        </div>
                        <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                            <select name="is_active" class="form-control">
                                <option value="">Select Status</option>
                                <option value="1">Active</option>
                                <option value="0">Inactive</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 text-right">
                            <input type="reset" name="reset" class="btn btn-primary" style="margin-top:25px;"
                                value="Reset" onClick="resetForm('searchform')">
                            <input type="submit" name="search" class="btn btn-primary" style="margin-top:25px;"
                                value="Search" id="searchBnt">
                            <br>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>