routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/clear-cache', function () {
    $exitCode = Artisan::call('config:cache');
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('view:clear');
    $exitCode = Artisan::call('route:clear');
    dd(Artisan::output());
});

// Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
// Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
// Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
// Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
// Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
// Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');
// Route::post('/set-password', 'CommonController@changePassword')->name('set-password');
//Before authentication
Route::group(['middleware' => 'beforeAuth'], function () {
    Route::get('/login', 'Admin\UsersController@login');
    Route::get('/backend', 'Admin\UsersController@login');
    Route::get('backend/login', 'Admin\UsersController@login')->name('backend.login');
    Route::get('backend/forgotPassword', 'Admin\UsersController@recoverPassword');
    Route::get('backend/resetPassword/{token}', 'Admin\UsersController@resetPassword');


    Route::post('login', 'Admin\UsersController@login');
    Route::post('recoverPassword', 'Admin\UsersController@recoverPassword');

    //client routes
    Route::get('/', 'CommonController@clientLoginIndex')->name('client-login-page');
    Route::post('/client-login', 'CommonController@clientLogin')->name('client.login');
    Route::get('/client-dashboard', 'CommonController@clientDashboard')->name('client.dashboard');
    Route::post('/logout', 'CommonController@clientLogout')->name('client.logout');
    Route::post('/store-ticket', 'CommonController@storeTicket')->name('store.ticket');
    Route::get('/pending-ticket', 'CommonController@getPendingTicket')->name('pending.ticket');

    Route::post('/set-password', 'CommonController@changePassword')->name('set-password');

    Route::get('change-password', 'CommonController@changeClientPassword');
    Route::post('changeClientOldPassword', 'CommonController@changeClientPassword');

    Route::get('resetPasswordClient/{token}', 'CommonController@resetPassword');
    Route::get('client-forgotPassword', 'CommonController@recoverPassword');
    Route::post('client-recoverPassword', 'CommonController@recoverPassword');

    Route::get('client-generate-work-order', 'TaskController@GenerateWorkOrder')->name('client.generate.work.order');
});


//After authentication with prefix:backend
Route::prefix('backend')->name('admin.')->middleware('checkAuth')->group(function () {
    Route::resource('users', 'Admin\UsersController');
    Route::match(['get', 'post'], '/users-list', 'Admin\UsersController@index')->name('users.index');

    Route::resource('roles', 'Admin\RolesController');
    Route::get('user-profile', 'Admin\UsersController@profileEdit');
    Route::get('reset-password-manually/{email}', 'Admin\UsersController@resetpasswordmanually');
    Route::get('change-password', 'Admin\UsersController@changePassword');
    Route::get('dashboard/{type?}', 'PagesController@dashboard');
    Route::post('logout', 'Admin\UsersController@logout')->name('logout');
    Route::patch('user-profile', 'Admin\UsersController@updateProfile')->name('user.profile');

    Route::resource('properties', 'PropertyController');
    Route::match(['get', 'post'], '/property-list', 'PropertyController@index')->name('property.index');

    Route::resource('clients', 'ClientController');
    Route::match(['get', 'post'], '/client-list', 'ClientController@index')->name('client.index');

    Route::resource('client_properties', 'ClientPropertyController');
    Route::match(['get', 'post'], '/client-property-list', 'ClientPropertyController@index')->name('client_properties.index');


    Route::resource('leads', 'LeadController');
    Route::get('/arcive-lead/{id?}', 'LeadController@archive_lead')->name('lead.archive');
    Route::match(['get', 'post'], '/lead-list', 'LeadController@index')->name('lead.index');


    // Route::get('tasks', 'TaskController@index')->name('task.index');
    // Route::post('tasks-check', 'TaskController@index')->name('task.check');
    Route::match(['get', 'post'], '/task-list/{type?}', 'TaskController@index')->name('task.index');
    Route::get('get-client', 'TaskController@getClientInfo')->name('get.client.info');
    Route::resource('tasks', 'TaskController');
    Route::get('tasks/{id}/edit/{completed?}', 'TaskController@edit')->name('tasks.edit');
    Route::get('workOrder-revert/{id}', 'TaskController@workOrderRevert');

    // Route::get('task-create', 'TaskController@taskCreate')->name('task.create');
    // Route::post('task-store', 'TaskController@taskStore')->name('task.store');
    Route::delete('task-delete/{id}', 'TaskController@destroy')->name('task.delete');
    // Route::get('task-edit/{id}', 'TaskController@edit')->name('task.edit');
    // Route::post('task-update/{id}', 'TaskController@update')->name('task.update');
    Route::get('schedule-edit/{id}/{completed?}', 'TaskController@scheduleEdit')->name('schedule.edit');
    Route::post('schedule-task-store/{id}', 'TaskController@ScheduleTaskStore')->name('schedule.task.store');
    Route::get('task-complete/{id}', 'TaskController@taskComplete')->name('task.complete');
    Route::get('task-incomplete/{id}', 'TaskController@taskInComplete')->name('task.incomplete');
    Route::get('task-unschedule/{id}', 'TaskController@taskUnschedule')->name('task.unschedule');
    Route::resource('items', 'ItemController');

    //Route::get('issue', 'IssueController@index')->name('issue.index');
    //Route::get('issue-create', 'IssueController@create')->name('issue.create');
    //Route::post('issue-store', 'IssueController@store')->name('issue.store');
    //Route::delete('issue-delete/{id}', 'IssueController@destroy')->name('issue.delete');
    //Route::get('issue-edit/{id}', 'IssueController@edit')->name('issue.edit');
    //Route::patch('issue-update/{id}', 'IssueController@update')->name('issue.update');

    Route::get('month-numbers', 'TaskController@getWeekNumbers')->name('get.month.numbers');

    Route::get('days-date', 'TaskController@decideComingDateAndNumberOfDays')->name('get.days.date');

    Route::get('reject-ticket', 'CommonController@ticketRejected')->name('ticket.reject');

    Route::get('generate-work-order', 'TaskController@GenerateWorkOrder')->name('generate.work.order');
    Route::get('delete-contract-file/{id}', 'PropertyController@deleteContractFile');

    Route::get('contracts/index/{client_id?}', 'ContractsController@index')->name('contracts.index');
    Route::get('contracts/allcontracts', 'ContractsController@allContracts')->name('contracts.allcontracts'); 
    Route::get('contracts/create/{client_id?}', 'ContractsController@create')->name('contracts.create');
    Route::post('contracts/store/{client_id?}', 'ContractsController@store')->name('contracts.store');

    Route::get('contracts/edit/{client_id?}/{id?}', 'ContractsController@edit')->name('contracts.edit');
    Route::put('contracts/update/{client_id?}/{id?}', 'ContractsController@update')->name('contracts.update');

    Route::get('retrieve_doc/{envelope_id?}', 'ContractsController@retrieveDocument')->name('retrieve_document');
    Route::get('update_contract_statuses', 'ContractsController@updateContractStatuses')->name('update_contract_statuses');

    Route::get('lists/index/{issue_id}', 'ItemController@listsIndex')->name('lists.index');

    Route::get('lists/create/{issue_id}', 'ItemController@listsCreate')->name('lists.create');
    Route::get('load/issue-list/{issue_id}', 'ItemController@issuesList');
    Route::get('lists/edit/{issue_id}/{id}', 'ItemController@listsEdit')->name('lists.edit');
    Route::post('lists/store/{issue_id}', 'ItemController@listsStore')->name('lists.store');
    Route::patch('lists/update/{issue_id}/{id}', 'ItemController@listsUpdate')->name('lists.update');
    Route::put('save-contract_tasks', 'ContractsController@contractTaskStore');
    Route::put('edit-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskUpdate');
    Route::put('add-images-contract_tasks/{contract_task_id}', 'ContractsController@contractTaskAddImages');

    Route::get('contract_task/edit/{id}', 'ContractsController@contractTaskEdit');
    Route::get('contract_task/upload_images/{id}', 'ContractsController@contractTaskUploadImages');
    Route::get('contract_task/all/{id}', 'ContractsController@getContractTask');
  
    Route::get('to-words/{value?}', 'ContractsController@toWords');
});

Route::post('changePassword', 'Admin\UsersController@changePassword');

app/Models/Issue.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use OwenIt\Auditing\Contracts\Auditable;

class Issue extends Model implements Auditable
{
    use HasFactory, SoftDeletes, \OwenIt\Auditing\Auditable;

    protected $fillable = [
        'issue',
        'is_active',
    ];

    public function task()
    {
        return $this->hasOne(Task::class, 'issue_id', 'id');
    }
}

resources/views/pages/issue/create.blade.php
@extends('master')
@section('title', 'Create Item')
@section('content')
    <div class="container">
        @if (Session::has('message'))
            <div class="row">
                <div class="container text-center">
                    <div class="alert alert-success">
                        {{ Session::get('message') }}
                    </div>
                </div>
            </div>
        @endif
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <h4 class="semi-bold text-center light-heading">{{ __('Create Item') }}</h4>

                    <div class="card-body">
                        <form method="POST" id="issue-form" action="{{ route('admin.items.store') }}">
                            @include('pages.issue.form')
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document.body).on('click', '#save-form', function() {
            $('#issue-form').validate({
                rules: {
                    issue: {
                        required: true,
                    },
                    is_active: {
                        required: true,
                    },

                },
                message: {

                },
                submitHandler: function(form) {
                    $("#submitForm").html("Please wait...").attr('disabled', true);
                    form.submit();
                }

            });

        });
    </script>
@endsection

resources/views/pages/issue/edit.blade.php
@extends('master')
@section('title', 'Issue Edit')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    <h4 class="semi-bold text-center light-heading">{{ __('Edit Item') }}</h4>
                    <div class="card-body">
                        <form id="issue-form" method="POST" action="{{ route('admin.items.update', $issue->id) }}">
                            @method('PATCH')
                            @include('pages.issue.form')
                        </form>
                        @can('task-type-delete')
                            @if ($issue->id)
                                <button class="btn btn-danger float-left"
                                    onClick="event.preventDefault();deleteConfirm('issue-delete-form-{{ $issue->id }}', 'You are about to delete a issue, Are you sure?')">
Delete                                
                                </button>
                                <form class="task_type-form" id="issue-delete-form-{{ $issue->id }}" style="display:none;"
                                    action="{{ route('admin.items.destroy', $issue->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            @endif
                        @endcan
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(document.body).on('click', '#save-form', function() {
            $('#issue-form').validate({
                rules: {
                    issue: {
                        lettersonly: true,
                        required: true,
                        maxlength: 45,
                        minlength: 2

                    },
                },
                message: {},
                submitHandler: function(form) {
                    $("#submitForm").html("Please wait...").attr('disabled', true);
                    form.submit();
                }

            });

        });
    </script>
@endsection

resources/views/pages/issue/form.blade.php
@csrf
<div class="row clearfix">
    <div class="col-md-12">
        <div class="form-group form-group-default required" aria-required="true">
            <label for="issue" class="col-md-12 col-form-label text-md-left">{{ __('Item') }}</label>
            <input id="issue" class="form-control @error('issue') is-invalid @enderror" name="issue"
                value="{{ old('issue') ?? $issue->issue }}" required autocomplete="issue" style="text-transform:uppercase">
            @error('issue')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-md-12">
        <div class="form-group form-group-default required">
            <label for="is_active" class="col-md-12 col-form-label text-md-left">{{ __('Status') }}</label>
            <select name="is_active" class="full-width" data-init-plugin="select2">
                <option value="">Select Status</option>
                <option value="1" @if ($issue->is_active == 1) {{ 'selected' }} @endif>Active</option>
                <option value="0" @if ($issue->is_active == 0) {{ 'selected' }} @endif>Inactive</option>
            </select>
            @error('is_active')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>
    </div>
</div>
<button id="save-form" type="submit" class="btn btn-primary float-right">
    @isset($issue->id)
        {{ __('Update') }}
    @else
        {{ __('Create') }}
    @endisset
</button>

resources/views/pages/issue/index.blade.php
@extends('master')
@section('title', 'Issue')
@section('content')
    <div>
        @if (Session::has('message'))
            <div class="row">
                <div class="container text-center">
                    <div class="alert alert-success message">
                        {{ Session::get('message') }}
                    </div>
                </div>
            </div>
        @endif
        <h1 class="float-left">Item Types List</h1>
        <div class="pull-left container">
            
            <i style="padding: 1px 9px;" data-toggle="tooltip" data-placement="top" title=""
            class="rounded-circle bg-primary ml-2 mr-2" data-original-title="Active"></i>
            <b>Active </b>
            
            <i style="padding: 1px 9px;" class="rounded-circle bg-danger ml-2 mr-2" data-toggle="tooltip" data-placement="top"
            title="" data-original-title="Inactive"></i>
            <b>Inactive </b>
            @can('client-create')
                <a href="{{ route('admin.items.create') }}" class="btn btn-primary float-right" role="button">Create Item</a>
            @endcan
        </div>
        <div class="clearfix"></div>
    </div>
    @include('pages.issue.list')

    @include('partials.loadmorejs')
    
   <script>
    $(document).ready(function() {
        setTimeout(() => {
            $('.message').fadeOut('slow');
        }, 3000);
    });
</script>
@endsection

resources/views/pages/issue/list.blade.php
@php
$issue_label1 = 'SR. No';
$issue_label2 = 'Item';
$issue_label3 = 'Status';
$issue_label4 = 'Action';
$serial = 0;
@endphp
<div class="container grid-wrapper p-3 mt-2">
    <div class="grid-header">
        <div class="row d-none d-md-flex mb-md-2 p-md-1">
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $issue_label1 }}</h4>
            </div>
            <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $issue_label2 }}</h4>
            </div>
            <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $issue_label3 }}</h4>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                <h4 class="small bold m-0">{{ $issue_label4 }}</h4>
            </div>
        </div>
    </div>
    <div class="grid-body">
        @foreach ($issues as $issue)
            @php
                $active = '<i style="" class="rounded-circle bg-primary" data-toggle="tooltip" data-placement="top" title=""></i>';
                $inactive = '<i style="" class="rounded-circle bg-danger" data-toggle="tooltip" data-placement="top" title=""></i>';
            @endphp
            <div class="row mb-md-0 p-md-1 mb-3 p-1">
                <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $issue_label1 }}</h4>
                    <p class="m-0 p-1">{{ ++$serial }}</p>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $issue_label2 }}</h4>
                    <p class="m-0 p-1 text-uppercase">{{ $issue->issue }}</p>
                </div>
                <div class="col-lg-1 col-md-1 col-sm-12 col-xs-12">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $issue_label3 }}</h4>
                    <p class="m-0 p-1">
                        @if ($issue->is_active == 1)
                            @php echo $active @endphp
                        @else
                            @php echo $inactive @endphp
                        @endif
                    </p>
                </div>
                <div class="col-3 col-sm-3 col-md-2">
                    <h4 class="d-md-none d-sm-inline bold small m-0 p-0">{{ $issue_label4 }}</h4>
                    <br class="d-none d-md-none d-sm-block " />
                    @can('task-type-edit')
                        <a href="{{ route('admin.lists.index', $issue->id) }}"
                            class="btn btn-primary mr-1 pt-1 pb-1 pl-2 pr-2" role="button">
                            Item Lists
                        </a>
                        <a href="{{ route('admin.items.edit', $issue->id) }}"
                            class="btn btn-primary mr-1 pt-1 pb-1 pl-2 pr-2" role="button">
                            Edit
                        </a>
                    @endcan
                    
                </div>
            </div> <!-- End of ROW -->
        @endforeach
    </div>
</div>
{{ $issues->links() }}